/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  AdminUserListResponse,
  AdminUserLoginListResponse,
  AdminUserStatsResponse,
  AdminUserUpdateRequest,
  DeleteUserApiAdminUsersUserIdDelete200,
  DeleteUserTransferApiAdminUsersUserIdTransfersUploadGroupDelete200,
  FileListResponse,
  ListUsersApiAdminUsersGetParams,
  UserResponse
} from '../../model';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
): Record<string, AngularHttpParamValueWithNullable> {
  const filteredParams: Record<string, AngularHttpParamValueWithNullable> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable({ providedIn: 'root' })
export class AdminService {
  private readonly http = inject(HttpClient);
/**
 * @summary List Users
 */
 listUsersApiAdminUsersGet<TData = AdminUserListResponse>(params?: ListUsersApiAdminUsersGetParams, options?: HttpClientBodyOptions): Observable<TData>;
 listUsersApiAdminUsersGet<TData = AdminUserListResponse>(params?: ListUsersApiAdminUsersGetParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listUsersApiAdminUsersGet<TData = AdminUserListResponse>(params?: ListUsersApiAdminUsersGetParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listUsersApiAdminUsersGet<TData = AdminUserListResponse>(
    params?: ListUsersApiAdminUsersGetParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/admin/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/admin/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/admin/users`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * @summary Update User
 */
 updateUserApiAdminUsersUserIdPatch<TData = UserResponse>(userId: number,
    adminUserUpdateRequest: AdminUserUpdateRequest, options?: HttpClientBodyOptions): Observable<TData>;
 updateUserApiAdminUsersUserIdPatch<TData = UserResponse>(userId: number,
    adminUserUpdateRequest: AdminUserUpdateRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 updateUserApiAdminUsersUserIdPatch<TData = UserResponse>(userId: number,
    adminUserUpdateRequest: AdminUserUpdateRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  updateUserApiAdminUsersUserIdPatch<TData = UserResponse>(
    userId: number,
    adminUserUpdateRequest: AdminUserUpdateRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/admin/users/${userId}`,
      adminUserUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/admin/users/${userId}`,
      adminUserUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/admin/users/${userId}`,
      adminUserUpdateRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Delete User
 */
 deleteUserApiAdminUsersUserIdDelete<TData = DeleteUserApiAdminUsersUserIdDelete200>(userId: number, options?: HttpClientBodyOptions): Observable<TData>;
 deleteUserApiAdminUsersUserIdDelete<TData = DeleteUserApiAdminUsersUserIdDelete200>(userId: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteUserApiAdminUsersUserIdDelete<TData = DeleteUserApiAdminUsersUserIdDelete200>(userId: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteUserApiAdminUsersUserIdDelete<TData = DeleteUserApiAdminUsersUserIdDelete200>(
    userId: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/admin/users/${userId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/admin/users/${userId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/admin/users/${userId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary List User Uploads
 */
 listUserUploadsApiAdminUsersUserIdUploadsGet<TData = FileListResponse>(userId: number, options?: HttpClientBodyOptions): Observable<TData>;
 listUserUploadsApiAdminUsersUserIdUploadsGet<TData = FileListResponse>(userId: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listUserUploadsApiAdminUsersUserIdUploadsGet<TData = FileListResponse>(userId: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listUserUploadsApiAdminUsersUserIdUploadsGet<TData = FileListResponse>(
    userId: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/admin/users/${userId}/uploads`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/admin/users/${userId}/uploads`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/admin/users/${userId}/uploads`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary List User Logins
 */
 listUserLoginsApiAdminUsersUserIdLoginsGet<TData = AdminUserLoginListResponse>(userId: number, options?: HttpClientBodyOptions): Observable<TData>;
 listUserLoginsApiAdminUsersUserIdLoginsGet<TData = AdminUserLoginListResponse>(userId: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listUserLoginsApiAdminUsersUserIdLoginsGet<TData = AdminUserLoginListResponse>(userId: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listUserLoginsApiAdminUsersUserIdLoginsGet<TData = AdminUserLoginListResponse>(
    userId: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/admin/users/${userId}/logins`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/admin/users/${userId}/logins`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/admin/users/${userId}/logins`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Get User Stats
 */
 getUserStatsApiAdminUsersUserIdStatsGet<TData = AdminUserStatsResponse>(userId: number, options?: HttpClientBodyOptions): Observable<TData>;
 getUserStatsApiAdminUsersUserIdStatsGet<TData = AdminUserStatsResponse>(userId: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getUserStatsApiAdminUsersUserIdStatsGet<TData = AdminUserStatsResponse>(userId: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getUserStatsApiAdminUsersUserIdStatsGet<TData = AdminUserStatsResponse>(
    userId: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/admin/users/${userId}/stats`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/admin/users/${userId}/stats`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/admin/users/${userId}/stats`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Delete User Transfer
 */
 deleteUserTransferApiAdminUsersUserIdTransfersUploadGroupDelete<TData = DeleteUserTransferApiAdminUsersUserIdTransfersUploadGroupDelete200>(userId: number,
    uploadGroup: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteUserTransferApiAdminUsersUserIdTransfersUploadGroupDelete<TData = DeleteUserTransferApiAdminUsersUserIdTransfersUploadGroupDelete200>(userId: number,
    uploadGroup: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteUserTransferApiAdminUsersUserIdTransfersUploadGroupDelete<TData = DeleteUserTransferApiAdminUsersUserIdTransfersUploadGroupDelete200>(userId: number,
    uploadGroup: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteUserTransferApiAdminUsersUserIdTransfersUploadGroupDelete<TData = DeleteUserTransferApiAdminUsersUserIdTransfersUploadGroupDelete200>(
    userId: number,
    uploadGroup: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/admin/users/${userId}/transfers/${uploadGroup}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/admin/users/${userId}/transfers/${uploadGroup}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/admin/users/${userId}/transfers/${uploadGroup}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

export type ListUsersApiAdminUsersGetClientResult = NonNullable<AdminUserListResponse>
export type UpdateUserApiAdminUsersUserIdPatchClientResult = NonNullable<UserResponse>
export type DeleteUserApiAdminUsersUserIdDeleteClientResult = NonNullable<DeleteUserApiAdminUsersUserIdDelete200>
export type ListUserUploadsApiAdminUsersUserIdUploadsGetClientResult = NonNullable<FileListResponse>
export type ListUserLoginsApiAdminUsersUserIdLoginsGetClientResult = NonNullable<AdminUserLoginListResponse>
export type GetUserStatsApiAdminUsersUserIdStatsGetClientResult = NonNullable<AdminUserStatsResponse>
export type DeleteUserTransferApiAdminUsersUserIdTransfersUploadGroupDeleteClientResult = NonNullable<DeleteUserTransferApiAdminUsersUserIdTransfersUploadGroupDelete200>
