/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */
import type { EmailRecipientInfo } from './emailRecipientInfo';
import type { PasswordInfo } from './passwordInfo';

export interface AccessInfoResponse {
  is_public: boolean;
  passwords: PasswordInfo[];
  emails: EmailRecipientInfo[];
  show_email_stats: boolean;
}
