/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */
import type { PasswordEntry } from './passwordEntry';

export interface AccessEditRequest {
  is_public?: boolean | null;
  show_email_stats?: boolean | null;
  passwords_to_add?: PasswordEntry[] | null;
  password_ids_to_remove?: number[] | null;
  emails_to_add?: string[] | null;
  email_ids_to_remove?: number[] | null;
}
