/**
 * SendR API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponse } from './user-response';


export interface AdminUserListResponse { 
    users: Array<UserResponse>;
    total: number;
}

