/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */

export interface AdminUserStatsResponse {
  total_transfers: number;
  active_transfers: number;
  total_files_uploaded: number;
  total_uploaded_bytes: number;
  total_downloads: number;
  login_count: number;
  last_login_at?: string | null;
}
