/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */

export interface BodyUploadMultipleFilesApiFilesUploadMultiplePost {
  files: Blob[];
  expiry_hours?: number | null;
  max_downloads?: number | null;
  is_public?: boolean;
  passwords?: string | null;
  emails?: string | null;
  show_email_stats?: boolean;
  title?: string | null;
  description?: string | null;
  altcha?: string;
}
