/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */

export interface ChangePasswordRequest {
  /**
     * @minLength 1
     * @maxLength 128
     */
  current_password: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  new_password: string;
}
