/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */

export interface CodeVerificationRequest {
  /** @pattern ^[^@\s]+@[^@\s]+\.[^@\s]+$ */
  email: string;
  /**
     * @minLength 6
     * @maxLength 6
     */
  code: string;
  create_account?: boolean;
}
