/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */

export interface FileUploadResponse {
  id: number;
  original_filename: string;
  file_size_bytes: number;
  download_url: string;
  expires_at: string;
  download_count: number;
  max_downloads?: number | null;
  is_active: boolean;
  upload_group?: string | null;
  message?: string | null;
  has_password?: boolean;
}
