/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */

export interface FileUploadResponse {
  id: number;
  original_filename: string;
  file_size_bytes: number;
  download_url: string;
  expires_at: string;
  download_count: number;
  public_download_count?: number;
  restricted_download_count?: number;
  max_downloads?: number | null;
  separate_download_counts?: boolean;
  is_active: boolean;
  upload_group?: string | null;
  message?: string | null;
  is_public?: boolean;
  has_passwords?: boolean;
  has_email_recipients?: boolean;
  viewer_is_owner?: boolean;
}
