/**
 * SendR API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileUploadResponse } from './file-upload-response';


export interface FileListResponse { 
    files: Array<FileUploadResponse>;
    quota_used: number;
    quota_limit: number;
}

