/**
 * SendR API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileUploadResponse { 
    id: number;
    original_filename: string;
    file_size_bytes: number;
    download_url: string;
    expires_at: string;
    download_count: number;
    is_active: boolean;
}

