/**
 * SendR API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileEditRequest { 
    original_filename?: string | null;
    message?: string | null;
    password?: string | null;
    remove_password?: boolean;
    expires_in_hours?: number | null;
    max_downloads?: number | null;
}

