/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */

export interface LimitsResponse {
  max_file_size_mb: number;
  max_files_per_upload: number;
  weekly_uploads_limit: number;
  expiry_options_hours: number[];
  max_downloads_options: number[];
  max_passwords_per_upload?: number;
  max_emails_per_upload?: number;
}
