/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */
import type { FileUploadResponse } from './fileUploadResponse';

export interface MultiFileUploadResponse {
  files: FileUploadResponse[];
  upload_group: string;
  total_size_bytes: number;
}
