/**
 * SendR API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuotaResponse { 
    max_file_size_mb: number;
    max_files_per_upload: number;
    weekly_uploads_limit: number;
    weekly_uploads_used: number;
    weekly_uploads_remaining: number;
    expiry_options_hours?: Array<number> | null;
    min_expiry_hours?: number | null;
    max_expiry_hours?: number | null;
    max_downloads_options?: Array<number> | null;
    max_downloads_limit?: number | null;
}

