/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */

export interface QuotaResponse {
  max_file_size_mb: number;
  max_files_per_upload: number;
  weekly_uploads_limit: number;
  weekly_uploads_used: number;
  weekly_uploads_remaining: number;
  expiry_options_hours?: number[] | null;
  min_expiry_hours?: number | null;
  max_expiry_hours?: number | null;
  max_downloads_options?: number[] | null;
  max_downloads_limit?: number | null;
}
