/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */
import type { RecipientDownloadEntry } from './recipientDownloadEntry';

export interface RecipientStatsResponse {
  downloads: RecipientDownloadEntry[];
  total_downloads: number;
}
