/**
 * SendR API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionResponse { 
    plan: string;
    is_active: boolean;
    started_at?: string | null;
    expires_at?: string | null;
}

