/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */

export interface SubscriptionResponse {
  plan: string;
  is_active: boolean;
  started_at?: string | null;
  expires_at?: string | null;
}
