/**
 * SendR API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileUploadResponse } from './file-upload-response';


export interface TransferInfoResponse { 
    upload_group: string;
    message?: string | null;
    sender_email?: string | null;
    has_password?: boolean;
    created_at: string;
    expires_at: string;
    files: Array<FileUploadResponse>;
    total_size_bytes: number;
    file_count: number;
}

