/**
 * SendR API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileUploadResponse } from './file-upload-response';


export interface UploadGroupInfoResponse { 
    files: Array<FileUploadResponse>;
    upload_group: string;
    total_size_bytes: number;
    file_count: number;
    will_zip: boolean;
}

