/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */
import type { FileUploadResponse } from './fileUploadResponse';

export interface UploadGroupInfoResponse {
  files: FileUploadResponse[];
  upload_group: string;
  total_size_bytes: number;
  file_count: number;
  will_zip: boolean;
  is_public?: boolean;
  has_passwords?: boolean;
  has_email_recipients?: boolean;
  title?: string | null;
  description?: string | null;
}
