apiVersion: ENC[AES256_GCM,data:FCQ=,iv:ZpM2pIvUyLpDyOkwQTGdqrR+/U3DpmAicL0c1tQNXw8=,tag:E+aTxRjOuLQuTe2aplRdNQ==,type:str]
kind: ENC[AES256_GCM,data:K+0fyWfH,iv:atEGoRrIreBYh/a3s7wtzCjP1zXPK/ijmxtx4x4SHBw=,tag:DXPB5OkplX98FpzdE5XPJw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6LHZGVtrsAmF8a6SJw==,iv:ktALmrFLjP7f/s3DtZ4DSxDYi+RwQCpM9TH0OJUNdvk=,tag:AEDyOR/inHmAjBNnkyjUSA==,type:str]
    namespace: ENC[AES256_GCM,data:FWe3t90=,iv:EU+MdEXF8xMD0A8u8D/j7CI2BpIwuMjE8f0q0jo37Bs=,tag:GfxJ8pLaRmxNpC4GiM2Otg==,type:str]
type: ENC[AES256_GCM,data:cY1mkUk8,iv:vb6bKAUd7I+dVnY4wd1D4CYFaDD0dlw2J7bvCVJd8ko=,tag:KhAQNyvvM+O4rv8aJEFVGA==,type:str]
stringData:
    environment: ENC[AES256_GCM,data:Gs48xyuDU8H2Nw==,iv:WhVN7aHgN2Y5Zqcov8nnsC5YMQqn/xepTiXZF64KUVI=,tag:BGwiyrvu+I0h7ycJIcPOcA==,type:str]
    database-url: ENC[AES256_GCM,data:tl6At4XStWEcR36G4gzrf9fX1MbjX3cPpndUW77f5f0nt982ebLlg0w61TLahD2Xn2n8lWDuLGrpNDVnpPtuG+UKDUoQyG2WWOFSTMNpyVH781QCfLYBAA9od+HFiE46sOEQi0aaMXoScD88ZPZqrqqgumDcsMzSepAYGW9BWbPU9aNiAcpDaZlFjLyz0sA=,iv:Q25QCy9TyXzgYRFLdnYoUezkiIRxgO/CHjoOi/2cBPI=,tag:ve/d0ushLuKBCRSGfvu7rA==,type:str]
    secret-key: ENC[AES256_GCM,data:x4MfYZhQGeOefj7bYF+Ytbvib7IuYHu+JZoKp8BWTtiPsFaxbIcedIXqCvPvMQ3aBsPr/49Jf3EehYxwUjGEUw==,iv:6Q3kkyAiShtc1TswfaDfGmqeM04eaGwO155GjSAPIso=,tag:v+ZwODL2PgPq86/3mPfucA==,type:str]
    altcha-hmac-key: ENC[AES256_GCM,data:sWo0rBSh3lgO2WBcJgfg552lDPTY7pG/2xOYYOXz02Q/x5kgwAUlXtUL4rtTSLq5oKMru6xhHC3vSIXC+G9QIQ==,iv:xKRKlr/W14Pp1SJQML0YiqsIzEzbvgv023SSzd+3bYg=,tag:qbpCqGPLjLW/yI0FVC/I9A==,type:str]
    smtp-host: ENC[AES256_GCM,data:4y4izCdTTrauTNAL/iYh,iv:Z1B6mPzKFYeTYMYNQAV75STaDcWdgNEKqFtijf9wxwk=,tag:TV+Ad2LWVwDFshK7KuwJHA==,type:str]
    smtp-port: ENC[AES256_GCM,data:h55Q,iv:TI4s3shVyeDdy98FliIx3bpO4rqzbduic+v0c8AS1tg=,tag:M2xfZO0/FuIAEmwMvfa8PQ==,type:str]
    smtp-user: ENC[AES256_GCM,data:8J2RG25D,iv:K8x2XQVumTcsq3ftO9pc8KfthUVeZeMaYj2T3+tymm4=,tag:PQWMwzHe25CIFrF+gho7Xg==,type:str]
    smtp-password: ENC[AES256_GCM,data:Hbwg5BN1UJxdVSyQZHPJDpTex3c6Kz/sm5H9Yu7B8qIZHH6v,iv:zn+woONlxCmR6OJS9MBSlbRdeGlCAMYmphvcWOHqW4U=,tag:JV/1HvDtHe4DqMKQ1OGNvw==,type:str]
    resend-api-key: ENC[AES256_GCM,data:HMpXtZDh84QZ1Ghw7ompGa19UTImXYvXMLFFuw4nj3xTwF5q,iv:Ef7X51F4AxBJcfXuf/Z2PNouAW1bXjOa5yEiPZA0ZyQ=,tag:uVSkWhjlkB1M1b+Za/rzFQ==,type:str]
    spaces-access-key: ENC[AES256_GCM,data:Z+3Ln81nvOfDR0PkiPCen/ToFRM=,iv:YkAbq5S5Qv4dIIEhR3b9Wi9zDvVSmHX2kjeIOYqZAfk=,tag:pgOcVnLGPzfGxOmxsgaiEQ==,type:str]
    spaces-secret-key: ENC[AES256_GCM,data:0rD7mHcSBFGjfeI0ZKtlB3w9Pa/vOyv1/wrHHzcwKOzFDOfL4ILY6jP1UQ==,iv:cEfY9giKSE2vbeDbRF5ZSbofcAwZhkeAgRcPoBmErzI=,tag:jPukIV0FU9uqeGU0Y31lGg==,type:str]
    spaces-bucket-name: ENC[AES256_GCM,data:xQCfcxtYYvRcG0Hx7l563wInv4r1Ep0=,iv:2P2AgCcBTNANg8VZRyDQOdM4nzvFiran0oFouqTiftw=,tag:lyGnFEMji8/vHZ6e8ptT8g==,type:str]
    spaces-region: ENC[AES256_GCM,data:Jo6Bzg==,iv:pqFhO2sWSf1FLJybhEdQfYP+i+wMePupSwbSxQvApSI=,tag:aKa3Xev9mYVz4Iuw/9/MxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWVQxdzNsMHh5VS9QRCtt
            Y0JUS3NCcnJKUnJvbGJVZ1B5aVpjenY3VTFjCnBkckQxWjRJWDNLdXlnTTExQjhK
            UlAzYjh0T1R0NmRXTWJib2pDTmlmSmsKLS0tIFQwemx0Z2RweU40dllyMUlIZWtp
            am9yaWF0TFhwNnRsL05WWStXN2ZvQUEKYjqcWoXR/fJehEObbTYjHPu1ab65LIZW
            VKtLfKuOJMYc2hCZP+oWg3kpTI2q1XqrorSwF3L0WvTZA5WKDIV5BA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10fpy52s5999vgpv3xz69gnhghealyjss95hduasy3er36wl09e8qy8t5gn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d3gzSzJkRDA3cUdIQ3VN
            S09pQUU0SDJEZER0QVhzN2wrN3dMOG9FVmhJClFDT25GZ2lSbDM5eC9ZSyt5MW5N
            TjZReFVDZU5ZSHEyTDF5WTJxTDVFNmsKLS0tIEZTWWZjNjMvTUNVM1o5VmJIQStl
            NDBtR2cxVE5XUlhiTXY3bXc4SGxJMG8KUYxhzBIGed0wo6G11Si7A75ijmeuvDqQ
            M/rEtAgL3JFoDT8pPSeCKJYXW9y6gw75HMOvKsFPpvPadL40pnfHpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ru3d425t9sxv6mexp2d60kpd3qryv3gt0y224srq9dfv4rcu6awsgyyta8
    lastmodified: "2026-05-23T15:00:04Z"
    mac: ENC[AES256_GCM,data:pAgQqL+Y7GFZROo128CMkH7dt2H50E//051RDHGlkCnLtlgjgeektXB2pPJ0rIWwdwhMBBpspFilf8I7EJBKsiVgaN14Usjt/mvfbRI5bKNXbt4Av6mbliYOdO17ifMZJsHUpYyMcdMwCDMYWUG6xW6/W/wKAMqrlHso/UbyYMk=,iv:6UhYxmzJvYn30iD1TvoCKKt22nZyxEPwPsq8X8xMjCY=,tag:cYznhGwOG81ZDNUMFhkNZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
