apiVersion: ENC[AES256_GCM,data:RBM=,iv:ZpM2pIvUyLpDyOkwQTGdqrR+/U3DpmAicL0c1tQNXw8=,tag:yucQfYXnuUwMo50dVvm/Pw==,type:str]
kind: ENC[AES256_GCM,data:RSFYWtTA,iv:atEGoRrIreBYh/a3s7wtzCjP1zXPK/ijmxtx4x4SHBw=,tag:I3iDebH/ZOppifKz8b9a8A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4crTJ/uNmlOG2BYpsw==,iv:ktALmrFLjP7f/s3DtZ4DSxDYi+RwQCpM9TH0OJUNdvk=,tag:AS5+Y7ZkVYTZNDlzkASFrA==,type:str]
    namespace: ENC[AES256_GCM,data:u3eVF1E=,iv:EU+MdEXF8xMD0A8u8D/j7CI2BpIwuMjE8f0q0jo37Bs=,tag:40XPr7+L8bN5r8azHaabSQ==,type:str]
type: ENC[AES256_GCM,data:DVJvZ8U4,iv:vb6bKAUd7I+dVnY4wd1D4CYFaDD0dlw2J7bvCVJd8ko=,tag:atfIWI7S6lirL4eaYaIH4w==,type:str]
stringData:
    environment: ENC[AES256_GCM,data:iu5DJcT/IQiAUQ==,iv:WhVN7aHgN2Y5Zqcov8nnsC5YMQqn/xepTiXZF64KUVI=,tag:UoAmdAIulqLW4mU8E2nAXA==,type:str]
    database-url: ENC[AES256_GCM,data:9H8HfR+GuO/0C+9uyRq5t3+gmyLNmXKQ0P3CAfkX6Fpdy0Xq3TEnwfNLkdkq8fQRLXrNqf7hHmolh2qPeMvnDWgL55/FR34yyewDvk+81WgVv+ngUzWazuNpdoltN8BH5Te6i0CraD9wXeDHd6KcumkUj/4CGJY3jLRMlSwVeXc361sUW3r+WQ4lyTEFX/A=,iv:Q25QCy9TyXzgYRFLdnYoUezkiIRxgO/CHjoOi/2cBPI=,tag:7dJKh9w5qBzHAjCKjw6DAw==,type:str]
    secret-key: ENC[AES256_GCM,data:AL8X2vLXDmiwOMRWG3d4ocWyE0imu1zr+hDEVcgBvQjMIVT9ZNqMIiKCxGoOMS9gKMbA7s74Bxpjpl+XuWUWMA==,iv:6Q3kkyAiShtc1TswfaDfGmqeM04eaGwO155GjSAPIso=,tag:b9e4AxmnHVZ8nU36IwPkNw==,type:str]
    altcha-hmac-key: ENC[AES256_GCM,data:GmCdZd0mkJuyg0ktpZfeknCkKp2sfrtYpVBrAfLKi65Phd4yhsmrvY+LQSz8as/sfG+/Dq5NqfWGmGWxB62oaA==,iv:xKRKlr/W14Pp1SJQML0YiqsIzEzbvgv023SSzd+3bYg=,tag:1CJyd4+nayXtGMK9f0gD0A==,type:str]
    smtp-host: ENC[AES256_GCM,data:y6OPg7PyYlZy6AixCHZ7,iv:Z1B6mPzKFYeTYMYNQAV75STaDcWdgNEKqFtijf9wxwk=,tag:Kb7tQoTi7LjWrR6TV6TA5A==,type:str]
    smtp-port: ENC[AES256_GCM,data:qIbd,iv:TI4s3shVyeDdy98FliIx3bpO4rqzbduic+v0c8AS1tg=,tag:NngM8a0vBZOwRmRhbOuSDw==,type:str]
    smtp-user: ENC[AES256_GCM,data:WGoaAzTI,iv:K8x2XQVumTcsq3ftO9pc8KfthUVeZeMaYj2T3+tymm4=,tag:NLSrj7NmmKyvbizv6onBrg==,type:str]
    smtp-password: ENC[AES256_GCM,data:6Y/itVM4sSopNusQtYmQD+sikUTdSM51A4rjuoTqgQy2KsjD,iv:zn+woONlxCmR6OJS9MBSlbRdeGlCAMYmphvcWOHqW4U=,tag:dhElHJNMOJllF0THKsDZ1g==,type:str]
    resend-api-key: ENC[AES256_GCM,data:wNoA+Uo+4Pv3U4MwuUgQSatOTJkT+crSMfn23xtD1C3zudHm,iv:Ef7X51F4AxBJcfXuf/Z2PNouAW1bXjOa5yEiPZA0ZyQ=,tag:wCWC77sdrekRRrkPCkzpyQ==,type:str]
    spaces-access-key: ENC[AES256_GCM,data:JhbtDBWItFGNdPriAajHy7qjkkQ=,iv:YkAbq5S5Qv4dIIEhR3b9Wi9zDvVSmHX2kjeIOYqZAfk=,tag:1wP/XZywaTBvDuDxWXPI7w==,type:str]
    spaces-secret-key: ENC[AES256_GCM,data:jY4bq14VTaGgDLQIy2MT4R8lwoOHFwVX2kK/SHd4jI/o1GhUebTF94rQ/Q==,iv:cEfY9giKSE2vbeDbRF5ZSbofcAwZhkeAgRcPoBmErzI=,tag:AOrmBfH4X95aeibDM5GSLg==,type:str]
    spaces-bucket-name: ENC[AES256_GCM,data:JsYI5HygugHjdRxnxr+LPKDlI0kLzZM=,iv:2P2AgCcBTNANg8VZRyDQOdM4nzvFiran0oFouqTiftw=,tag:A3s5pXJtuOFyfYDiBr7EIw==,type:str]
    spaces-region: ENC[AES256_GCM,data:8r8W9g==,iv:pqFhO2sWSf1FLJybhEdQfYP+i+wMePupSwbSxQvApSI=,tag:qWdcuWk6RLkcpi9bPva5VA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN1V6QjJ5UnB1OVdQc2Rn
            SXpDQ25zUnFaOStjRmVwdkJLbW0zMW5mL2tRCnduZTVnNlV0SEcycW04TGZ0ZW8x
            T1h0M00xTklwY2tUZTB4dzRFZTlRWjAKLS0tIG8yL0w2V2NmYWJCcmlkN3RzdFp3
            ODExcC9NQ0NyT3hHMTJtdFhPQ1QxdlEK1JACI2rU17Fr5erTK0QC9fywcWhuNAbj
            h6iLZBJ3khqSsXlrhS+Lq+dVdTop2GLOCNnIK/lW+/pWiUwSqO8LtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10fpy52s5999vgpv3xz69gnhghealyjss95hduasy3er36wl09e8qy8t5gn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWmluUGxZT2RWK3dsemwx
            WVFoWnVFVnVuOG9Ra2ZSbzJVVVgyUURYUlF3Cm95cXJZMjk2K2UxOE1jOEdPVEU1
            cGFXWFZTN1BuSHVVcHVOOVhvU0Z6OTgKLS0tIGZGTEIreCs5QnRwalNzeDhNMzlz
            K1ByVlpWSmFjeldUbjZGNSswaEI3VzAKBM2G0MT2NeOFCUZ4e++mqVu2SO+vyWB9
            e5D38jIq3FrdbN9rChL5/MC4Q5c1ork9+cpIqmV8Aha0uJL7NlREpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ru3d425t9sxv6mexp2d60kpd3qryv3gt0y224srq9dfv4rcu6awsgyyta8
    lastmodified: "2026-05-23T15:15:43Z"
    mac: ENC[AES256_GCM,data:Vpgz7DyIT/qBvwGRckR4gWc24Q5H2oe0dtrJ7t42lCy4MtX8fpuHooDNSindPuE7XEJ95d/fm8LNwOfqM0IHAQP7Hld5f67ngqXX1tIMg4DSEfWefioSsQ4BjjM/8D4/274908dZAMO50CSGeKu3qqLFLHdLctXBSWcrezYFdzI=,iv:7GTD9yt3Fn1S/G2Uz7qIBQg1x1JGPdgRgjZ3qlGBI+k=,tag:7QNuRlX2WhgnvIiPGWmT3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
