apiVersion: ENC[AES256_GCM,data:MjA=,iv:rQLyxj1UyuPuT75TF7TpjGZsD29qGWqxR7wSqC/gtfM=,tag:6hchGPpsa88fQk5woyVypA==,type:str]
kind: ENC[AES256_GCM,data:0j/J/9kY,iv:/YjDTvhLNbDBNNz8MtWPDHSo+1vpxldhrgq6U/iIfHE=,tag:yzTvMJOdnYFrmmu/Lms+ow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RpJ3n0pUsPsxv47ygw==,iv:nfj5dH59zVm7GecoOycBRG64ei5soAeQ4GPZs+c7E6w=,tag:NvrJX5m0qbPSLa+ASBUWcw==,type:str]
    namespace: ENC[AES256_GCM,data:cLl17jc=,iv:u5NbFF5x5lWFg+bqOzEbyGtLQDA5iJHRpxubp3K0dYA=,tag:UebGycvY2uFSSH6dy5ungQ==,type:str]
type: ENC[AES256_GCM,data:hHebfAKC,iv:hjFDXwpiDHu2z9pdKia4buF6DPBuHT8DG4ic4JFwJXw=,tag:7AqSxqJvQYFDFOsPCSHzpQ==,type:str]
stringData:
    environment: ENC[AES256_GCM,data:YCpnnD3t1Jzsfg==,iv:k0/XMhxpv+b74cUCO9SgPmuabZeiYil0kLFf/IWiwBM=,tag:xICxGYVitzSDkrQcZp6FoQ==,type:str]
    database-url: ENC[AES256_GCM,data:jI6yYBny9gzCcKAhXDzPS7YaWO3F2dw4cJfb6XPjY+bv8HHvnDgNrlSjsJWM8qTjTVC/OhoAfneOR4y2063x3OiC1YuvcNgWswAiZJd50Wb/EUHgMin4DRNgGrrJzmtn43wQaYnH7L0Wsk9RXu1SOy9IhBl0f0rsuCS35PDkG4MaJtcpJbGU1VpDEaYJBTc=,iv:fZP8wbc5Mgvh0ow1VMz0kOYtzeAORfsbcSHhIsPYVqY=,tag:tzadaMELlltL5gUJbUbYuQ==,type:str]
    secret-key: ENC[AES256_GCM,data:bwB1zRTJeo5q/dSgO1+jiwODhKM287ZhdzWfwxPDRpce8z8PYWBqWfg32RxM6hJxfCmFatXoEYJKxzACHb4OgA==,iv:MK0I4Q0bSDq0yZWJ2typiiHwFfHHVPAoRf04+3HIo24=,tag:I2swUzjPkB6yPjl7vbQaWQ==,type:str]
    altcha-hmac-key: ENC[AES256_GCM,data:VLEVFvhE44U3d1opMee1sCMA2y7BmVAKvY7Db3lB1CnC9+zgu66z0TdR/mkix8eNro5CxxbaDTjv+bdddyrJnA==,iv:fWKlRUpMANq1Ym2AE0qUXOcHrUCdRKkveLX3e6Zsq4I=,tag:IC/rxIBy6R+bBi/2uQ8JCA==,type:str]
    smtp-host: ENC[AES256_GCM,data:uAco0e98Z3rKyLvsdQyO,iv:/NjareyVKfPZOyjfeeY1NlC2LUNAQxnk+/N7XGlacJg=,tag:ZWIFuo6KH1rSGdviW50NCg==,type:str]
    smtp-port: ENC[AES256_GCM,data:YX/f,iv:ZdIfKw8qBvR26eYwVQyOWkgJrMU/JkyRdBl+Ti4DPUA=,tag:pZBtID1BJZsl9gSrt4i2Dw==,type:str]
    smtp-user: ENC[AES256_GCM,data:q4SqxwuU,iv:SWp5xQSM1pbmzdXP0ZUZ265nMxzlNL1ehm8uhI8ZruY=,tag:R4QKj0ybm55ROOgul7xz9A==,type:str]
    smtp-password: ENC[AES256_GCM,data:t8k/3Bf7AOtjTqgK/JrM9qDW3aasV5JDRCOvlfljmSzUzXiO,iv:dfP11QLLXW1nHkvtG5WjLQ18PcohnL0Kx23F+fbFuoo=,tag:RZaIAlWvEVwvMv9P+u+5Zg==,type:str]
    resend-api-key: ENC[AES256_GCM,data:7bRAtx/I1GnpODx2sbri9DSmuMabPbhmF8fRkqK4UdgNzDJJ,iv:hu0Xy5710jfLGXW4EgtIq08eAUSDhHd5OeYTBvD94K4=,tag:xeu9WbH6srbtLNZKCnbEbA==,type:str]
    spaces-access-key: ENC[AES256_GCM,data:nUTk4mqUjhGFZXKfjVrmRl1CAHQ=,iv:RFUXcwPDC8ArbDhUdHJpkkLrfPCCxCNlNyKkqy6sMgY=,tag:TQhuOmZwqgaF6UGj8jh8jA==,type:str]
    spaces-secret-key: ENC[AES256_GCM,data:KfOJqBa/6P/G0bu0mnjX6p3Jw+c1qJYJ2g8aYpeg/ziBJB8nTLSl7IPi5A==,iv:av1I+BwHc69MraXUJwVxMTA/IREzeUgrCDAZ6LnIduY=,tag:tbOl+QyvaM2j4BM5VeNOWQ==,type:str]
    spaces-bucket-name: ENC[AES256_GCM,data:Fjiu5CRm8VZ4lpESYz8Sx5B2icuIKwI=,iv:pl7nLigHjyZP002kQ8i83HYKV8AeCE/m7V8i5AhMFpg=,tag:Zo3pESScpmNjDBIFFI2qeg==,type:str]
    spaces-region: ENC[AES256_GCM,data:k53OcA==,iv:uakpY1FX9x8FyVv15NTnuHBgnITB0rfXbYyXYXA/H6E=,tag:9OTtUuaG+pWlrBrlVgZzZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQXcwejNUWVFzckdYeTJJ
            WStpT3RyTEdGYXlhU0FkZ3Z3ZU9uKy9iNVNNCnk0eTI0MnBTY1k5REtNWDI3YzZR
            a1FZK3RTV2lBMUZETmJGekZoRFFad1UKLS0tIEluREpQdng4THdsam4xajVVRkkz
            YlA0T1A0S1ptZVlsUVpGck5rOTVaZjgKPbLJIjKmTauOJowNmA3jZBhSXM+qENvQ
            n2vYSJ2vfEx2+jM+IP/Zxbc6GrQCCYgHZopkxzi3G7GNo9d1/g4GTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158h7nj4qws73majldt3kptxrfy908wn3fezv4v2uuc9zmqudgapsmlq408
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR1RxdEZLTFVJRHlmSUVP
            dEZCaUJUZW0xSVhhNkN0NU1KWmJ0aVhta2tBCnZkMWtiUVNEUU1mV1R3aTNUSlZw
            azlMRHhJQWFWVnVQbGNicWhDeGFVLzQKLS0tIDdrM1h6R05aRnhyOVZReFptM1ln
            T1ZTSHo1Y2tQL1YzY1VOcDd6SjFsZ1EKB7aKhEwn1H2myzLyD5wB/OpOg234owTe
            3YDjT0QXms5NrhaWaTMYKCXp9PoFS5PYrRCzleHIgiLIeMwkzLAsYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ru3d425t9sxv6mexp2d60kpd3qryv3gt0y224srq9dfv4rcu6awsgyyta8
    lastmodified: "2026-05-23T15:27:40Z"
    mac: ENC[AES256_GCM,data:+vhLmzcH2BnA0e2XxTUep0vNga4jaXvfXYysM1CT930jAHhOFHnGWVxY/m4iRJ0CZwadigZa3/RPmQnIl3FCO8zwf7PooZzsiTLxPMuPyy6YeW/eDrxw7X8CEQewPBbR7nXYdGnKlflEzFatTf3vqzUE1Rrun7xTEe469p/jYq8=,iv:PF4vHT9LUARmITmHIVvcrPT1ilpQSD332HMtLeQj++s=,tag:/TredkUL0AtCfaoOovp/vQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
