/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  ChangePasswordRequest,
  CodeVerificationRequest,
  EmailVerificationRequest,
  LimitsResponse,
  PasswordLoginRequest,
  QuotaResponse,
  RequestCodeApiAuthRequestCodePost200,
  SetPasswordRequest,
  TokenResponse,
  UserResponse
} from '../../model';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class AuthService {
  private readonly http = inject(HttpClient);
/**
 * @summary Request Code
 */
 requestCodeApiAuthRequestCodePost<TData = RequestCodeApiAuthRequestCodePost200>(emailVerificationRequest: EmailVerificationRequest, options?: HttpClientBodyOptions): Observable<TData>;
 requestCodeApiAuthRequestCodePost<TData = RequestCodeApiAuthRequestCodePost200>(emailVerificationRequest: EmailVerificationRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 requestCodeApiAuthRequestCodePost<TData = RequestCodeApiAuthRequestCodePost200>(emailVerificationRequest: EmailVerificationRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  requestCodeApiAuthRequestCodePost<TData = RequestCodeApiAuthRequestCodePost200>(
    emailVerificationRequest: EmailVerificationRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/auth/request-code`,
      emailVerificationRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/auth/request-code`,
      emailVerificationRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/auth/request-code`,
      emailVerificationRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Verify Code
 */
 verifyCodeApiAuthVerifyCodePost<TData = TokenResponse>(codeVerificationRequest: CodeVerificationRequest, options?: HttpClientBodyOptions): Observable<TData>;
 verifyCodeApiAuthVerifyCodePost<TData = TokenResponse>(codeVerificationRequest: CodeVerificationRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 verifyCodeApiAuthVerifyCodePost<TData = TokenResponse>(codeVerificationRequest: CodeVerificationRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  verifyCodeApiAuthVerifyCodePost<TData = TokenResponse>(
    codeVerificationRequest: CodeVerificationRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/auth/verify-code`,
      codeVerificationRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/auth/verify-code`,
      codeVerificationRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/auth/verify-code`,
      codeVerificationRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Login Password
 */
 loginPasswordApiAuthLoginPasswordPost<TData = TokenResponse>(passwordLoginRequest: PasswordLoginRequest, options?: HttpClientBodyOptions): Observable<TData>;
 loginPasswordApiAuthLoginPasswordPost<TData = TokenResponse>(passwordLoginRequest: PasswordLoginRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 loginPasswordApiAuthLoginPasswordPost<TData = TokenResponse>(passwordLoginRequest: PasswordLoginRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  loginPasswordApiAuthLoginPasswordPost<TData = TokenResponse>(
    passwordLoginRequest: PasswordLoginRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/auth/login-password`,
      passwordLoginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/auth/login-password`,
      passwordLoginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/auth/login-password`,
      passwordLoginRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Get Me
 */
 getMeApiAuthMeGet<TData = UserResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 getMeApiAuthMeGet<TData = UserResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getMeApiAuthMeGet<TData = UserResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getMeApiAuthMeGet<TData = UserResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/auth/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/auth/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/auth/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Set Password
 */
 setPasswordApiAuthSetPasswordPost<TData = UserResponse>(setPasswordRequest: SetPasswordRequest, options?: HttpClientBodyOptions): Observable<TData>;
 setPasswordApiAuthSetPasswordPost<TData = UserResponse>(setPasswordRequest: SetPasswordRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 setPasswordApiAuthSetPasswordPost<TData = UserResponse>(setPasswordRequest: SetPasswordRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  setPasswordApiAuthSetPasswordPost<TData = UserResponse>(
    setPasswordRequest: SetPasswordRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/auth/set-password`,
      setPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/auth/set-password`,
      setPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/auth/set-password`,
      setPasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Change Password
 */
 changePasswordApiAuthChangePasswordPost<TData = UserResponse>(changePasswordRequest: ChangePasswordRequest, options?: HttpClientBodyOptions): Observable<TData>;
 changePasswordApiAuthChangePasswordPost<TData = UserResponse>(changePasswordRequest: ChangePasswordRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 changePasswordApiAuthChangePasswordPost<TData = UserResponse>(changePasswordRequest: ChangePasswordRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  changePasswordApiAuthChangePasswordPost<TData = UserResponse>(
    changePasswordRequest: ChangePasswordRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/auth/change-password`,
      changePasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/auth/change-password`,
      changePasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/auth/change-password`,
      changePasswordRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Return upload limits for temporary tier (public, no auth required).
 * @summary Get Limits
 */
 getLimitsApiAuthLimitsGet<TData = LimitsResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 getLimitsApiAuthLimitsGet<TData = LimitsResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getLimitsApiAuthLimitsGet<TData = LimitsResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getLimitsApiAuthLimitsGet<TData = LimitsResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/auth/limits`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/auth/limits`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/auth/limits`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Get Quota
 */
 getQuotaApiAuthQuotaGet<TData = QuotaResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 getQuotaApiAuthQuotaGet<TData = QuotaResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getQuotaApiAuthQuotaGet<TData = QuotaResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getQuotaApiAuthQuotaGet<TData = QuotaResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/auth/quota`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/auth/quota`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/auth/quota`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

