.PHONY: init plan apply destroy

init:
	cd environments/dev && terraform init

plan:
	cd environments/dev && terraform plan

apply:
	cd environments/dev && terraform apply

destroy:
	cd environments/dev && terraform destroy

validate:
	cd environments/dev && terraform validate