from typing import BinaryIO

class ClamdError(Exception): ...
class BufferTooLongError(ClamdError): ...

class ClamdNetworkSocket:
    def __init__(self, host: str = ..., port: int = ...) -> None: ...
    def instream(
        self, stream: BinaryIO
    ) -> dict[str, tuple[str, str | None]] | None: ...

class ClamdUnixSocket:
    def __init__(self, path: str = ...) -> None: ...
    def instream(
        self, stream: BinaryIO
    ) -> dict[str, tuple[str, str | None]] | None: ...
