/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */
import type {
  AccessInfoResponse,
  AdminUserListResponse,
  DownloadFileApiFilesDownloadTokenGetParams,
  DownloadGroupApiFilesGroupUploadGroupDownloadGetParams,
  DownloadStatsResponse,
  FileListResponse,
  FileUploadResponse,
  GetChallengeApiAltchaChallengeGet200,
  GetRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetParams,
  LimitsResponse,
  ListUsersApiAdminUsersGetParams,
  QuotaResponse,
  RecipientStatsResponse,
  SubscriptionResponse,
  UploadGroupInfoResponse,
  UserResponse
} from '../model';

import {
  httpResource
} from '@angular/common/http';
import type {
  HttpResourceOptions,
  HttpResourceRef
} from '@angular/common/http';

import type {
  ResourceStatus,
  Signal
} from '@angular/core';


export type OrvalHttpResourceOptions<TValue, TRaw = unknown, TOmitParse extends boolean = false> = TOmitParse extends true
  ? Omit<HttpResourceOptions<TValue, TRaw>, 'parse'>
  : HttpResourceOptions<TValue, TRaw>;

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
): Record<string, AngularHttpParamValueWithNullable> {
  const filteredParams: Record<string, AngularHttpParamValueWithNullable> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}
/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function listUsersApiAdminUsersGetResource(params: Signal<ListUsersApiAdminUsersGetParams> | undefined,
  options: OrvalHttpResourceOptions<AdminUserListResponse, unknown> & { defaultValue: NoInfer<AdminUserListResponse> }): HttpResourceRef<AdminUserListResponse>;
export function listUsersApiAdminUsersGetResource(params?: Signal<ListUsersApiAdminUsersGetParams>,
  options?: OrvalHttpResourceOptions<AdminUserListResponse, unknown>): HttpResourceRef<AdminUserListResponse | undefined>;
export function listUsersApiAdminUsersGetResource(params?: Signal<ListUsersApiAdminUsersGetParams>,
  options?: OrvalHttpResourceOptions<AdminUserListResponse, unknown>): HttpResourceRef<AdminUserListResponse | undefined> {
  return httpResource<AdminUserListResponse>(() => {
    
    const request = ({
      url: `/api/admin/users`,
      params: filterParams(params?.() ?? {}, new Set<string>([]))
    });
    return request;
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function getChallengeApiAltchaChallengeGetResource(options: OrvalHttpResourceOptions<GetChallengeApiAltchaChallengeGet200, unknown> & { defaultValue: NoInfer<GetChallengeApiAltchaChallengeGet200> }): HttpResourceRef<GetChallengeApiAltchaChallengeGet200>;
export function getChallengeApiAltchaChallengeGetResource(options?: OrvalHttpResourceOptions<GetChallengeApiAltchaChallengeGet200, unknown>): HttpResourceRef<GetChallengeApiAltchaChallengeGet200 | undefined>;
export function getChallengeApiAltchaChallengeGetResource(options?: OrvalHttpResourceOptions<GetChallengeApiAltchaChallengeGet200, unknown>): HttpResourceRef<GetChallengeApiAltchaChallengeGet200 | undefined> {
  return httpResource<GetChallengeApiAltchaChallengeGet200>(() => `/api/altcha/challenge`, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function getMeApiAuthMeGetResource(options: OrvalHttpResourceOptions<UserResponse, unknown> & { defaultValue: NoInfer<UserResponse> }): HttpResourceRef<UserResponse>;
export function getMeApiAuthMeGetResource(options?: OrvalHttpResourceOptions<UserResponse, unknown>): HttpResourceRef<UserResponse | undefined>;
export function getMeApiAuthMeGetResource(options?: OrvalHttpResourceOptions<UserResponse, unknown>): HttpResourceRef<UserResponse | undefined> {
  return httpResource<UserResponse>(() => `/api/auth/me`, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function getLimitsApiAuthLimitsGetResource(options: OrvalHttpResourceOptions<LimitsResponse, unknown> & { defaultValue: NoInfer<LimitsResponse> }): HttpResourceRef<LimitsResponse>;
export function getLimitsApiAuthLimitsGetResource(options?: OrvalHttpResourceOptions<LimitsResponse, unknown>): HttpResourceRef<LimitsResponse | undefined>;
export function getLimitsApiAuthLimitsGetResource(options?: OrvalHttpResourceOptions<LimitsResponse, unknown>): HttpResourceRef<LimitsResponse | undefined> {
  return httpResource<LimitsResponse>(() => `/api/auth/limits`, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function getQuotaApiAuthQuotaGetResource(options: OrvalHttpResourceOptions<QuotaResponse, unknown> & { defaultValue: NoInfer<QuotaResponse> }): HttpResourceRef<QuotaResponse>;
export function getQuotaApiAuthQuotaGetResource(options?: OrvalHttpResourceOptions<QuotaResponse, unknown>): HttpResourceRef<QuotaResponse | undefined>;
export function getQuotaApiAuthQuotaGetResource(options?: OrvalHttpResourceOptions<QuotaResponse, unknown>): HttpResourceRef<QuotaResponse | undefined> {
  return httpResource<QuotaResponse>(() => `/api/auth/quota`, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function getGroupInfoApiFilesGroupUploadGroupGetResource(uploadGroup: Signal<string>,
  options: OrvalHttpResourceOptions<UploadGroupInfoResponse, unknown> & { defaultValue: NoInfer<UploadGroupInfoResponse> }): HttpResourceRef<UploadGroupInfoResponse>;
export function getGroupInfoApiFilesGroupUploadGroupGetResource(uploadGroup: Signal<string>,
  options?: OrvalHttpResourceOptions<UploadGroupInfoResponse, unknown>): HttpResourceRef<UploadGroupInfoResponse | undefined>;
export function getGroupInfoApiFilesGroupUploadGroupGetResource(uploadGroup: Signal<string>,
  options?: OrvalHttpResourceOptions<UploadGroupInfoResponse, unknown>): HttpResourceRef<UploadGroupInfoResponse | undefined> {
  return httpResource<UploadGroupInfoResponse>(() => `/api/files/group/${uploadGroup()}`, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function downloadGroupApiFilesGroupUploadGroupDownloadGetResource(uploadGroup: Signal<string>,
    params: Signal<DownloadGroupApiFilesGroupUploadGroupDownloadGetParams> | undefined,
  options: OrvalHttpResourceOptions<unknown, unknown> & { defaultValue: NoInfer<unknown> }): HttpResourceRef<unknown>;
export function downloadGroupApiFilesGroupUploadGroupDownloadGetResource(uploadGroup: Signal<string>,
    params?: Signal<DownloadGroupApiFilesGroupUploadGroupDownloadGetParams>,
  options?: OrvalHttpResourceOptions<unknown, unknown>): HttpResourceRef<unknown | undefined>;
export function downloadGroupApiFilesGroupUploadGroupDownloadGetResource(uploadGroup: Signal<string>,
    params?: Signal<DownloadGroupApiFilesGroupUploadGroupDownloadGetParams>,
  options?: OrvalHttpResourceOptions<unknown, unknown>): HttpResourceRef<unknown | undefined> {
  return httpResource<unknown>(() => {
    
    const request = ({
      url: `/api/files/group/${uploadGroup()}/download`,
      params: filterParams(params?.() ?? {}, new Set<string>([]))
    });
    return request;
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function listFilesApiFilesGetResource(options: OrvalHttpResourceOptions<FileListResponse, unknown> & { defaultValue: NoInfer<FileListResponse> }): HttpResourceRef<FileListResponse>;
export function listFilesApiFilesGetResource(options?: OrvalHttpResourceOptions<FileListResponse, unknown>): HttpResourceRef<FileListResponse | undefined>;
export function listFilesApiFilesGetResource(options?: OrvalHttpResourceOptions<FileListResponse, unknown>): HttpResourceRef<FileListResponse | undefined> {
  return httpResource<FileListResponse>(() => `/api/files/`, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function downloadFileApiFilesDownloadTokenGetResource(downloadToken: Signal<string>,
    params: Signal<DownloadFileApiFilesDownloadTokenGetParams> | undefined,
  options: OrvalHttpResourceOptions<unknown, unknown> & { defaultValue: NoInfer<unknown> }): HttpResourceRef<unknown>;
export function downloadFileApiFilesDownloadTokenGetResource(downloadToken: Signal<string>,
    params?: Signal<DownloadFileApiFilesDownloadTokenGetParams>,
  options?: OrvalHttpResourceOptions<unknown, unknown>): HttpResourceRef<unknown | undefined>;
export function downloadFileApiFilesDownloadTokenGetResource(downloadToken: Signal<string>,
    params?: Signal<DownloadFileApiFilesDownloadTokenGetParams>,
  options?: OrvalHttpResourceOptions<unknown, unknown>): HttpResourceRef<unknown | undefined> {
  return httpResource<unknown>(() => {
    
    const request = ({
      url: `/api/files/${downloadToken()}`,
      params: filterParams(params?.() ?? {}, new Set<string>([]))
    });
    return request;
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function getFileInfoApiFilesDownloadTokenInfoGetResource(downloadToken: Signal<string>,
  options: OrvalHttpResourceOptions<FileUploadResponse, unknown> & { defaultValue: NoInfer<FileUploadResponse> }): HttpResourceRef<FileUploadResponse>;
export function getFileInfoApiFilesDownloadTokenInfoGetResource(downloadToken: Signal<string>,
  options?: OrvalHttpResourceOptions<FileUploadResponse, unknown>): HttpResourceRef<FileUploadResponse | undefined>;
export function getFileInfoApiFilesDownloadTokenInfoGetResource(downloadToken: Signal<string>,
  options?: OrvalHttpResourceOptions<FileUploadResponse, unknown>): HttpResourceRef<FileUploadResponse | undefined> {
  return httpResource<FileUploadResponse>(() => `/api/files/${downloadToken()}/info`, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function getAccessInfoApiFilesGroupUploadGroupAccessInfoGetResource(uploadGroup: Signal<string>,
  options: OrvalHttpResourceOptions<AccessInfoResponse, unknown> & { defaultValue: NoInfer<AccessInfoResponse> }): HttpResourceRef<AccessInfoResponse>;
export function getAccessInfoApiFilesGroupUploadGroupAccessInfoGetResource(uploadGroup: Signal<string>,
  options?: OrvalHttpResourceOptions<AccessInfoResponse, unknown>): HttpResourceRef<AccessInfoResponse | undefined>;
export function getAccessInfoApiFilesGroupUploadGroupAccessInfoGetResource(uploadGroup: Signal<string>,
  options?: OrvalHttpResourceOptions<AccessInfoResponse, unknown>): HttpResourceRef<AccessInfoResponse | undefined> {
  return httpResource<AccessInfoResponse>(() => `/api/files/group/${uploadGroup()}/access-info`, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function getGroupStatsApiFilesGroupUploadGroupStatsGetResource(uploadGroup: Signal<string>,
  options: OrvalHttpResourceOptions<DownloadStatsResponse, unknown> & { defaultValue: NoInfer<DownloadStatsResponse> }): HttpResourceRef<DownloadStatsResponse>;
export function getGroupStatsApiFilesGroupUploadGroupStatsGetResource(uploadGroup: Signal<string>,
  options?: OrvalHttpResourceOptions<DownloadStatsResponse, unknown>): HttpResourceRef<DownloadStatsResponse | undefined>;
export function getGroupStatsApiFilesGroupUploadGroupStatsGetResource(uploadGroup: Signal<string>,
  options?: OrvalHttpResourceOptions<DownloadStatsResponse, unknown>): HttpResourceRef<DownloadStatsResponse | undefined> {
  return httpResource<DownloadStatsResponse>(() => `/api/files/group/${uploadGroup()}/stats`, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function getRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetResource(uploadGroup: Signal<string>,
    params: Signal<GetRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetParams> | undefined,
  options: OrvalHttpResourceOptions<RecipientStatsResponse, unknown> & { defaultValue: NoInfer<RecipientStatsResponse> }): HttpResourceRef<RecipientStatsResponse>;
export function getRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetResource(uploadGroup: Signal<string>,
    params?: Signal<GetRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetParams>,
  options?: OrvalHttpResourceOptions<RecipientStatsResponse, unknown>): HttpResourceRef<RecipientStatsResponse | undefined>;
export function getRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetResource(uploadGroup: Signal<string>,
    params?: Signal<GetRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetParams>,
  options?: OrvalHttpResourceOptions<RecipientStatsResponse, unknown>): HttpResourceRef<RecipientStatsResponse | undefined> {
  return httpResource<RecipientStatsResponse>(() => {
    
    const request = ({
      url: `/api/files/group/${uploadGroup()}/recipient-stats`,
      params: filterParams(params?.() ?? {}, new Set<string>([]))
    });
    return request;
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function getSubscriptionApiSubscriptionGetResource(options: OrvalHttpResourceOptions<SubscriptionResponse, unknown> & { defaultValue: NoInfer<SubscriptionResponse> }): HttpResourceRef<SubscriptionResponse>;
export function getSubscriptionApiSubscriptionGetResource(options?: OrvalHttpResourceOptions<SubscriptionResponse, unknown>): HttpResourceRef<SubscriptionResponse | undefined>;
export function getSubscriptionApiSubscriptionGetResource(options?: OrvalHttpResourceOptions<SubscriptionResponse, unknown>): HttpResourceRef<SubscriptionResponse | undefined> {
  return httpResource<SubscriptionResponse>(() => `/api/subscription`, options);
}

export type ListUsersApiAdminUsersGetResourceResult = NonNullable<AdminUserListResponse>
export type GetChallengeApiAltchaChallengeGetResourceResult = NonNullable<GetChallengeApiAltchaChallengeGet200>
export type GetMeApiAuthMeGetResourceResult = NonNullable<UserResponse>
export type GetLimitsApiAuthLimitsGetResourceResult = NonNullable<LimitsResponse>
export type GetQuotaApiAuthQuotaGetResourceResult = NonNullable<QuotaResponse>
export type GetGroupInfoApiFilesGroupUploadGroupGetResourceResult = NonNullable<UploadGroupInfoResponse>
export type DownloadGroupApiFilesGroupUploadGroupDownloadGetResourceResult = NonNullable<unknown>
export type ListFilesApiFilesGetResourceResult = NonNullable<FileListResponse>
export type DownloadFileApiFilesDownloadTokenGetResourceResult = NonNullable<unknown>
export type GetFileInfoApiFilesDownloadTokenInfoGetResourceResult = NonNullable<FileUploadResponse>
export type GetAccessInfoApiFilesGroupUploadGroupAccessInfoGetResourceResult = NonNullable<AccessInfoResponse>
export type GetGroupStatsApiFilesGroupUploadGroupStatsGetResourceResult = NonNullable<DownloadStatsResponse>
export type GetRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetResourceResult = NonNullable<RecipientStatsResponse>
export type GetSubscriptionApiSubscriptionGetResourceResult = NonNullable<SubscriptionResponse>

/**
 * Utility type for httpResource results with status tracking.
 * Inspired by @angular-architects/ngrx-toolkit withResource pattern.
 *
 * Uses `globalThis.Error` to avoid collision with API model types named `Error`.
 */
export interface ResourceState<T> {
  readonly value: Signal<T | undefined>;
  readonly status: Signal<ResourceStatus>;
  readonly error: Signal<globalThis.Error | undefined>;
  readonly isLoading: Signal<boolean>;
  readonly hasValue: () => boolean;
  readonly reload: () => boolean;
}

/**
 * Wraps an HttpResourceRef to expose a consistent ResourceState interface.
 * Useful when integrating with NgRx SignalStore via withResource().
 */
export function toResourceState<T>(ref: HttpResourceRef<T>): ResourceState<T> {
  return {
    value: ref.value,
    status: ref.status,
    error: ref.error,
    isLoading: ref.isLoading,
    hasValue: () => ref.hasValue(),
    reload: () => ref.reload(),
  };
}
