/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  SubscriptionResponse
} from '../../model';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class SubscriptionService {
  private readonly http = inject(HttpClient);
/**
 * @summary Get Subscription
 */
 getSubscriptionApiSubscriptionGet<TData = SubscriptionResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 getSubscriptionApiSubscriptionGet<TData = SubscriptionResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getSubscriptionApiSubscriptionGet<TData = SubscriptionResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getSubscriptionApiSubscriptionGet<TData = SubscriptionResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/subscription`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/subscription`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/subscription`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Mock upgrade to premium. In production, this would integrate with a payment provider.
 * @summary Upgrade To Premium
 */
 upgradeToPremiumApiSubscriptionUpgradePost<TData = SubscriptionResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 upgradeToPremiumApiSubscriptionUpgradePost<TData = SubscriptionResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 upgradeToPremiumApiSubscriptionUpgradePost<TData = SubscriptionResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  upgradeToPremiumApiSubscriptionUpgradePost<TData = SubscriptionResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/subscription/upgrade`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/subscription/upgrade`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/subscription/upgrade`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Cancel premium subscription. Downgrades user to free tier.
 * @summary Cancel Subscription
 */
 cancelSubscriptionApiSubscriptionCancelPost<TData = SubscriptionResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 cancelSubscriptionApiSubscriptionCancelPost<TData = SubscriptionResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 cancelSubscriptionApiSubscriptionCancelPost<TData = SubscriptionResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  cancelSubscriptionApiSubscriptionCancelPost<TData = SubscriptionResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/subscription/cancel`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/subscription/cancel`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/subscription/cancel`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

