"""add_transfer_model

Revision ID: 8cb9b35cf603
Revises: c1d2e3f4a5b6
Create Date: 2026-03-26 10:19:16.261651

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cb9b35cf603"
down_revision: str | Sequence[str] | None = "c1d2e3f4a5b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transfer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("upload_group", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("recipient_emails", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notify_on_download", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transfer", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transfer_upload_group"), ["upload_group"], unique=True)
        batch_op.create_index(batch_op.f("ix_transfer_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "tier",
            existing_type=sa.VARCHAR(length=9),
            type_=sa.Enum("basic", "free", "premium", name="usertier"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "tier",
            existing_type=sa.Enum("basic", "free", "premium", name="usertier"),
            type_=sa.VARCHAR(length=9),
            existing_nullable=False,
        )

    with op.batch_alter_table("transfer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transfer_user_id"))
        batch_op.drop_index(batch_op.f("ix_transfer_upload_group"))

    op.drop_table("transfer")
    # ### end Alembic commands ###
