"""initial_migration

Revision ID: acf42cd55a38
Revises: 
Create Date: 2026-03-16 14:02:53.573774

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'acf42cd55a38'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier', sa.Enum('anonymous', 'free', 'premium', name='usertier'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('verificationcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verificationcode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verificationcode_email'), ['email'], unique=False)

    op.create_table('authtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authtoken_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_authtoken_user_id'), ['user_id'], unique=False)

    op.create_table('fileupload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('download_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fileupload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fileupload_download_token'), ['download_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_fileupload_user_id'), ['user_id'], unique=False)

    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'premium', name='subscriptionplan'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_user_id'))

    op.drop_table('subscription')
    with op.batch_alter_table('fileupload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fileupload_user_id'))
        batch_op.drop_index(batch_op.f('ix_fileupload_download_token'))

    op.drop_table('fileupload')
    with op.batch_alter_table('authtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authtoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_authtoken_token'))

    op.drop_table('authtoken')
    with op.batch_alter_table('verificationcode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verificationcode_email'))

    op.drop_table('verificationcode')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
