apiVersion: apps/v1
kind: Deployment
metadata:
  name: sendr-clamav
  namespace: sendr
  labels:
    app: sendr-clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sendr-clamav
  template:
    metadata:
      labels:
        app: sendr-clamav
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: clamav
          image: clamav/clamav:1.4.4_base-debian13-slim@sha256:ea10abbccfb35ecd8ea257808728f12e84e64ce4d84502134ab7d3b7ed3a2270
          imagePullPolicy: IfNotPresent
          env:
            - name: CLAMD_CONF_StreamMaxLength
              value: 10G
            - name: CLAMD_CONF_MaxFileSize
              value: 10G
            - name: CLAMD_CONF_MaxScanSize
              value: 10G
          ports:
            - containerPort: 3310
              name: clamd
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          startupProbe:
            tcpSocket:
              port: clamd
            periodSeconds: 10
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: clamd
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: clamd
            periodSeconds: 30
            failureThreshold: 3
          volumeMounts:
            - name: clamav-db
              mountPath: /var/lib/clamav
      volumes:
        - name: clamav-db
          emptyDir: {}