/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  BodyUploadFileApiFilesUploadPost,
  BodyUploadMultipleFilesApiFilesUploadMultiplePost,
  DeactivateFileApiFilesFileIdDelete200,
  FileListResponse,
  FileUploadResponse,
  MultiFileUploadResponse,
  UploadGroupInfoResponse
} from '../../model';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class FilesService {
  private readonly http = inject(HttpClient);
/**
 * @summary Upload File
 */
 uploadFileApiFilesUploadPost<TData = FileUploadResponse>(bodyUploadFileApiFilesUploadPost: BodyUploadFileApiFilesUploadPost, options?: HttpClientBodyOptions): Observable<TData>;
 uploadFileApiFilesUploadPost<TData = FileUploadResponse>(bodyUploadFileApiFilesUploadPost: BodyUploadFileApiFilesUploadPost, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 uploadFileApiFilesUploadPost<TData = FileUploadResponse>(bodyUploadFileApiFilesUploadPost: BodyUploadFileApiFilesUploadPost, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  uploadFileApiFilesUploadPost<TData = FileUploadResponse>(
    bodyUploadFileApiFilesUploadPost: BodyUploadFileApiFilesUploadPost, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
formData.append(`file`, bodyUploadFileApiFilesUploadPost.file);
if(bodyUploadFileApiFilesUploadPost.expiry_hours !== undefined && bodyUploadFileApiFilesUploadPost.expiry_hours !== null) {
 formData.append(`expiry_hours`, bodyUploadFileApiFilesUploadPost.expiry_hours.toString())
 }
if(bodyUploadFileApiFilesUploadPost.max_downloads !== undefined && bodyUploadFileApiFilesUploadPost.max_downloads !== null) {
 formData.append(`max_downloads`, bodyUploadFileApiFilesUploadPost.max_downloads.toString())
 }
if(bodyUploadFileApiFilesUploadPost.altcha !== undefined) {
 formData.append(`altcha`, bodyUploadFileApiFilesUploadPost.altcha);
 }

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/files/upload`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/files/upload`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/files/upload`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Upload Multiple Files
 */
 uploadMultipleFilesApiFilesUploadMultiplePost<TData = MultiFileUploadResponse>(bodyUploadMultipleFilesApiFilesUploadMultiplePost: BodyUploadMultipleFilesApiFilesUploadMultiplePost, options?: HttpClientBodyOptions): Observable<TData>;
 uploadMultipleFilesApiFilesUploadMultiplePost<TData = MultiFileUploadResponse>(bodyUploadMultipleFilesApiFilesUploadMultiplePost: BodyUploadMultipleFilesApiFilesUploadMultiplePost, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 uploadMultipleFilesApiFilesUploadMultiplePost<TData = MultiFileUploadResponse>(bodyUploadMultipleFilesApiFilesUploadMultiplePost: BodyUploadMultipleFilesApiFilesUploadMultiplePost, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  uploadMultipleFilesApiFilesUploadMultiplePost<TData = MultiFileUploadResponse>(
    bodyUploadMultipleFilesApiFilesUploadMultiplePost: BodyUploadMultipleFilesApiFilesUploadMultiplePost, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
bodyUploadMultipleFilesApiFilesUploadMultiplePost.files.forEach(value => formData.append(`files`, value));
if(bodyUploadMultipleFilesApiFilesUploadMultiplePost.expiry_hours !== undefined && bodyUploadMultipleFilesApiFilesUploadMultiplePost.expiry_hours !== null) {
 formData.append(`expiry_hours`, bodyUploadMultipleFilesApiFilesUploadMultiplePost.expiry_hours.toString())
 }
if(bodyUploadMultipleFilesApiFilesUploadMultiplePost.max_downloads !== undefined && bodyUploadMultipleFilesApiFilesUploadMultiplePost.max_downloads !== null) {
 formData.append(`max_downloads`, bodyUploadMultipleFilesApiFilesUploadMultiplePost.max_downloads.toString())
 }
if(bodyUploadMultipleFilesApiFilesUploadMultiplePost.altcha !== undefined) {
 formData.append(`altcha`, bodyUploadMultipleFilesApiFilesUploadMultiplePost.altcha);
 }

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/files/upload-multiple`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/files/upload-multiple`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/files/upload-multiple`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Get Group Info
 */
 getGroupInfoApiFilesGroupUploadGroupGet<TData = UploadGroupInfoResponse>(uploadGroup: string, options?: HttpClientBodyOptions): Observable<TData>;
 getGroupInfoApiFilesGroupUploadGroupGet<TData = UploadGroupInfoResponse>(uploadGroup: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getGroupInfoApiFilesGroupUploadGroupGet<TData = UploadGroupInfoResponse>(uploadGroup: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getGroupInfoApiFilesGroupUploadGroupGet<TData = UploadGroupInfoResponse>(
    uploadGroup: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/files/group/${uploadGroup}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Download Group
 */
 downloadGroupApiFilesGroupUploadGroupDownloadGet<TData = unknown>(uploadGroup: string, options?: HttpClientBodyOptions): Observable<TData>;
 downloadGroupApiFilesGroupUploadGroupDownloadGet<TData = unknown>(uploadGroup: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 downloadGroupApiFilesGroupUploadGroupDownloadGet<TData = unknown>(uploadGroup: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  downloadGroupApiFilesGroupUploadGroupDownloadGet<TData = unknown>(
    uploadGroup: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/download`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary List Files
 */
 listFilesApiFilesGet<TData = FileListResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 listFilesApiFilesGet<TData = FileListResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listFilesApiFilesGet<TData = FileListResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listFilesApiFilesGet<TData = FileListResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/files/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Download File
 */
 downloadFileApiFilesDownloadTokenGet<TData = unknown>(downloadToken: string, options?: HttpClientBodyOptions): Observable<TData>;
 downloadFileApiFilesDownloadTokenGet<TData = unknown>(downloadToken: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 downloadFileApiFilesDownloadTokenGet<TData = unknown>(downloadToken: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  downloadFileApiFilesDownloadTokenGet<TData = unknown>(
    downloadToken: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/${downloadToken}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/${downloadToken}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/files/${downloadToken}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Get File Info
 */
 getFileInfoApiFilesDownloadTokenInfoGet<TData = FileUploadResponse>(downloadToken: string, options?: HttpClientBodyOptions): Observable<TData>;
 getFileInfoApiFilesDownloadTokenInfoGet<TData = FileUploadResponse>(downloadToken: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getFileInfoApiFilesDownloadTokenInfoGet<TData = FileUploadResponse>(downloadToken: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getFileInfoApiFilesDownloadTokenInfoGet<TData = FileUploadResponse>(
    downloadToken: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/${downloadToken}/info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/${downloadToken}/info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/files/${downloadToken}/info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Refresh Download Link
 */
 refreshDownloadLinkApiFilesFileIdRefreshPost<TData = FileUploadResponse>(fileId: number, options?: HttpClientBodyOptions): Observable<TData>;
 refreshDownloadLinkApiFilesFileIdRefreshPost<TData = FileUploadResponse>(fileId: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 refreshDownloadLinkApiFilesFileIdRefreshPost<TData = FileUploadResponse>(fileId: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  refreshDownloadLinkApiFilesFileIdRefreshPost<TData = FileUploadResponse>(
    fileId: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/files/${fileId}/refresh`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/files/${fileId}/refresh`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/files/${fileId}/refresh`,undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Deactivate File
 */
 deactivateFileApiFilesFileIdDelete<TData = DeactivateFileApiFilesFileIdDelete200>(fileId: number, options?: HttpClientBodyOptions): Observable<TData>;
 deactivateFileApiFilesFileIdDelete<TData = DeactivateFileApiFilesFileIdDelete200>(fileId: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deactivateFileApiFilesFileIdDelete<TData = DeactivateFileApiFilesFileIdDelete200>(fileId: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deactivateFileApiFilesFileIdDelete<TData = DeactivateFileApiFilesFileIdDelete200>(
    fileId: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/files/${fileId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/files/${fileId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/files/${fileId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

