/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SendR API
 * WeTransfer-like file sharing service
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  AccessInfoResponse,
  BodyAddFilesToGroupApiFilesGroupUploadGroupAddPost,
  BodyUploadFileApiFilesUploadPost,
  BodyUploadMultipleFilesApiFilesUploadMultiplePost,
  DeactivateFileApiFilesFileIdDelete200,
  DownloadFileApiFilesDownloadTokenGetParams,
  DownloadGroupApiFilesGroupUploadGroupDownloadGetParams,
  DownloadStatsResponse,
  FileEditRequest,
  FileListResponse,
  FileUploadResponse,
  GetRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetParams,
  GroupEditRequest,
  GroupRefreshRequest,
  MultiFileUploadResponse,
  RecipientStatsResponse,
  RefreshDownloadLinkApiFilesFileIdRefreshPostParams,
  UploadGroupInfoResponse
} from '../../model';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
): Record<string, AngularHttpParamValueWithNullable> {
  const filteredParams: Record<string, AngularHttpParamValueWithNullable> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable({ providedIn: 'root' })
export class FilesService {
  private readonly http = inject(HttpClient);
/**
 * @summary Upload File
 */
 uploadFileApiFilesUploadPost<TData = FileUploadResponse>(bodyUploadFileApiFilesUploadPost: BodyUploadFileApiFilesUploadPost, options?: HttpClientBodyOptions): Observable<TData>;
 uploadFileApiFilesUploadPost<TData = FileUploadResponse>(bodyUploadFileApiFilesUploadPost: BodyUploadFileApiFilesUploadPost, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 uploadFileApiFilesUploadPost<TData = FileUploadResponse>(bodyUploadFileApiFilesUploadPost: BodyUploadFileApiFilesUploadPost, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  uploadFileApiFilesUploadPost<TData = FileUploadResponse>(
    bodyUploadFileApiFilesUploadPost: BodyUploadFileApiFilesUploadPost, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
formData.append(`file`, bodyUploadFileApiFilesUploadPost.file);
if(bodyUploadFileApiFilesUploadPost.expiry_hours !== undefined && bodyUploadFileApiFilesUploadPost.expiry_hours !== null) {
 formData.append(`expiry_hours`, bodyUploadFileApiFilesUploadPost.expiry_hours.toString())
 }
if(bodyUploadFileApiFilesUploadPost.max_downloads !== undefined && bodyUploadFileApiFilesUploadPost.max_downloads !== null) {
 formData.append(`max_downloads`, bodyUploadFileApiFilesUploadPost.max_downloads.toString())
 }
if(bodyUploadFileApiFilesUploadPost.is_public !== undefined) {
 formData.append(`is_public`, bodyUploadFileApiFilesUploadPost.is_public.toString())
 }
if(bodyUploadFileApiFilesUploadPost.passwords !== undefined && bodyUploadFileApiFilesUploadPost.passwords !== null) {
 formData.append(`passwords`, bodyUploadFileApiFilesUploadPost.passwords);
 }
if(bodyUploadFileApiFilesUploadPost.emails !== undefined && bodyUploadFileApiFilesUploadPost.emails !== null) {
 formData.append(`emails`, bodyUploadFileApiFilesUploadPost.emails);
 }
if(bodyUploadFileApiFilesUploadPost.show_email_stats !== undefined) {
 formData.append(`show_email_stats`, bodyUploadFileApiFilesUploadPost.show_email_stats.toString())
 }
if(bodyUploadFileApiFilesUploadPost.altcha !== undefined) {
 formData.append(`altcha`, bodyUploadFileApiFilesUploadPost.altcha);
 }

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/files/upload`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/files/upload`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/files/upload`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Upload Multiple Files
 */
 uploadMultipleFilesApiFilesUploadMultiplePost<TData = MultiFileUploadResponse>(bodyUploadMultipleFilesApiFilesUploadMultiplePost: BodyUploadMultipleFilesApiFilesUploadMultiplePost, options?: HttpClientBodyOptions): Observable<TData>;
 uploadMultipleFilesApiFilesUploadMultiplePost<TData = MultiFileUploadResponse>(bodyUploadMultipleFilesApiFilesUploadMultiplePost: BodyUploadMultipleFilesApiFilesUploadMultiplePost, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 uploadMultipleFilesApiFilesUploadMultiplePost<TData = MultiFileUploadResponse>(bodyUploadMultipleFilesApiFilesUploadMultiplePost: BodyUploadMultipleFilesApiFilesUploadMultiplePost, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  uploadMultipleFilesApiFilesUploadMultiplePost<TData = MultiFileUploadResponse>(
    bodyUploadMultipleFilesApiFilesUploadMultiplePost: BodyUploadMultipleFilesApiFilesUploadMultiplePost, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
bodyUploadMultipleFilesApiFilesUploadMultiplePost.files.forEach(value => formData.append(`files`, value));
if(bodyUploadMultipleFilesApiFilesUploadMultiplePost.expiry_hours !== undefined && bodyUploadMultipleFilesApiFilesUploadMultiplePost.expiry_hours !== null) {
 formData.append(`expiry_hours`, bodyUploadMultipleFilesApiFilesUploadMultiplePost.expiry_hours.toString())
 }
if(bodyUploadMultipleFilesApiFilesUploadMultiplePost.max_downloads !== undefined && bodyUploadMultipleFilesApiFilesUploadMultiplePost.max_downloads !== null) {
 formData.append(`max_downloads`, bodyUploadMultipleFilesApiFilesUploadMultiplePost.max_downloads.toString())
 }
if(bodyUploadMultipleFilesApiFilesUploadMultiplePost.is_public !== undefined) {
 formData.append(`is_public`, bodyUploadMultipleFilesApiFilesUploadMultiplePost.is_public.toString())
 }
if(bodyUploadMultipleFilesApiFilesUploadMultiplePost.passwords !== undefined && bodyUploadMultipleFilesApiFilesUploadMultiplePost.passwords !== null) {
 formData.append(`passwords`, bodyUploadMultipleFilesApiFilesUploadMultiplePost.passwords);
 }
if(bodyUploadMultipleFilesApiFilesUploadMultiplePost.emails !== undefined && bodyUploadMultipleFilesApiFilesUploadMultiplePost.emails !== null) {
 formData.append(`emails`, bodyUploadMultipleFilesApiFilesUploadMultiplePost.emails);
 }
if(bodyUploadMultipleFilesApiFilesUploadMultiplePost.show_email_stats !== undefined) {
 formData.append(`show_email_stats`, bodyUploadMultipleFilesApiFilesUploadMultiplePost.show_email_stats.toString())
 }
if(bodyUploadMultipleFilesApiFilesUploadMultiplePost.altcha !== undefined) {
 formData.append(`altcha`, bodyUploadMultipleFilesApiFilesUploadMultiplePost.altcha);
 }

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/files/upload-multiple`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/files/upload-multiple`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/files/upload-multiple`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Get Group Info
 */
 getGroupInfoApiFilesGroupUploadGroupGet<TData = UploadGroupInfoResponse>(uploadGroup: string, options?: HttpClientBodyOptions): Observable<TData>;
 getGroupInfoApiFilesGroupUploadGroupGet<TData = UploadGroupInfoResponse>(uploadGroup: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getGroupInfoApiFilesGroupUploadGroupGet<TData = UploadGroupInfoResponse>(uploadGroup: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getGroupInfoApiFilesGroupUploadGroupGet<TData = UploadGroupInfoResponse>(
    uploadGroup: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/files/group/${uploadGroup}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Edit group settings without changing download links. Premium only.
 * @summary Edit Group
 */
 editGroupApiFilesGroupUploadGroupPatch<TData = MultiFileUploadResponse>(uploadGroup: string,
    groupEditRequest: GroupEditRequest, options?: HttpClientBodyOptions): Observable<TData>;
 editGroupApiFilesGroupUploadGroupPatch<TData = MultiFileUploadResponse>(uploadGroup: string,
    groupEditRequest: GroupEditRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 editGroupApiFilesGroupUploadGroupPatch<TData = MultiFileUploadResponse>(uploadGroup: string,
    groupEditRequest: GroupEditRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  editGroupApiFilesGroupUploadGroupPatch<TData = MultiFileUploadResponse>(
    uploadGroup: string,
    groupEditRequest: GroupEditRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/files/group/${uploadGroup}`,
      groupEditRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/files/group/${uploadGroup}`,
      groupEditRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/files/group/${uploadGroup}`,
      groupEditRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Download Group
 */
 downloadGroupApiFilesGroupUploadGroupDownloadGet<TData = unknown>(uploadGroup: string,
    params?: DownloadGroupApiFilesGroupUploadGroupDownloadGetParams, options?: HttpClientBodyOptions): Observable<TData>;
 downloadGroupApiFilesGroupUploadGroupDownloadGet<TData = unknown>(uploadGroup: string,
    params?: DownloadGroupApiFilesGroupUploadGroupDownloadGetParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 downloadGroupApiFilesGroupUploadGroupDownloadGet<TData = unknown>(uploadGroup: string,
    params?: DownloadGroupApiFilesGroupUploadGroupDownloadGetParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  downloadGroupApiFilesGroupUploadGroupDownloadGet<TData = unknown>(
    uploadGroup: string,
    params?: DownloadGroupApiFilesGroupUploadGroupDownloadGetParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/download`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/download`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/download`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * @summary List Files
 */
 listFilesApiFilesGet<TData = FileListResponse>( options?: HttpClientBodyOptions): Observable<TData>;
 listFilesApiFilesGet<TData = FileListResponse>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listFilesApiFilesGet<TData = FileListResponse>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listFilesApiFilesGet<TData = FileListResponse>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/files/`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Download File
 */
 downloadFileApiFilesDownloadTokenGet<TData = unknown>(downloadToken: string,
    params?: DownloadFileApiFilesDownloadTokenGetParams, options?: HttpClientBodyOptions): Observable<TData>;
 downloadFileApiFilesDownloadTokenGet<TData = unknown>(downloadToken: string,
    params?: DownloadFileApiFilesDownloadTokenGetParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 downloadFileApiFilesDownloadTokenGet<TData = unknown>(downloadToken: string,
    params?: DownloadFileApiFilesDownloadTokenGetParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  downloadFileApiFilesDownloadTokenGet<TData = unknown>(
    downloadToken: string,
    params?: DownloadFileApiFilesDownloadTokenGetParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/${downloadToken}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/${downloadToken}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/files/${downloadToken}`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * @summary Get File Info
 */
 getFileInfoApiFilesDownloadTokenInfoGet<TData = FileUploadResponse>(downloadToken: string, options?: HttpClientBodyOptions): Observable<TData>;
 getFileInfoApiFilesDownloadTokenInfoGet<TData = FileUploadResponse>(downloadToken: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getFileInfoApiFilesDownloadTokenInfoGet<TData = FileUploadResponse>(downloadToken: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getFileInfoApiFilesDownloadTokenInfoGet<TData = FileUploadResponse>(
    downloadToken: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/${downloadToken}/info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/${downloadToken}/info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/files/${downloadToken}/info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Refresh Download Link
 */
 refreshDownloadLinkApiFilesFileIdRefreshPost<TData = FileUploadResponse>(fileId: number,
    params?: RefreshDownloadLinkApiFilesFileIdRefreshPostParams, options?: HttpClientBodyOptions): Observable<TData>;
 refreshDownloadLinkApiFilesFileIdRefreshPost<TData = FileUploadResponse>(fileId: number,
    params?: RefreshDownloadLinkApiFilesFileIdRefreshPostParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 refreshDownloadLinkApiFilesFileIdRefreshPost<TData = FileUploadResponse>(fileId: number,
    params?: RefreshDownloadLinkApiFilesFileIdRefreshPostParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  refreshDownloadLinkApiFilesFileIdRefreshPost<TData = FileUploadResponse>(
    fileId: number,
    params?: RefreshDownloadLinkApiFilesFileIdRefreshPostParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/files/${fileId}/refresh`,undefined,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/files/${fileId}/refresh`,undefined,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.post<TData>(
      `/api/files/${fileId}/refresh`,undefined,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * Edit file metadata without changing the download link. Premium only.
 * @summary Edit File
 */
 editFileApiFilesFileIdPatch<TData = FileUploadResponse>(fileId: number,
    fileEditRequest: FileEditRequest, options?: HttpClientBodyOptions): Observable<TData>;
 editFileApiFilesFileIdPatch<TData = FileUploadResponse>(fileId: number,
    fileEditRequest: FileEditRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 editFileApiFilesFileIdPatch<TData = FileUploadResponse>(fileId: number,
    fileEditRequest: FileEditRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  editFileApiFilesFileIdPatch<TData = FileUploadResponse>(
    fileId: number,
    fileEditRequest: FileEditRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(
      `/api/files/${fileId}`,
      fileEditRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(
      `/api/files/${fileId}`,
      fileEditRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.patch<TData>(
      `/api/files/${fileId}`,
      fileEditRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Deactivate File
 */
 deactivateFileApiFilesFileIdDelete<TData = DeactivateFileApiFilesFileIdDelete200>(fileId: number, options?: HttpClientBodyOptions): Observable<TData>;
 deactivateFileApiFilesFileIdDelete<TData = DeactivateFileApiFilesFileIdDelete200>(fileId: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deactivateFileApiFilesFileIdDelete<TData = DeactivateFileApiFilesFileIdDelete200>(fileId: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deactivateFileApiFilesFileIdDelete<TData = DeactivateFileApiFilesFileIdDelete200>(
    fileId: number, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/files/${fileId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/files/${fileId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/files/${fileId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Add new files to an existing upload group. Requires ownership of the group.
 * @summary Add Files To Group
 */
 addFilesToGroupApiFilesGroupUploadGroupAddPost<TData = MultiFileUploadResponse>(uploadGroup: string,
    bodyAddFilesToGroupApiFilesGroupUploadGroupAddPost: BodyAddFilesToGroupApiFilesGroupUploadGroupAddPost, options?: HttpClientBodyOptions): Observable<TData>;
 addFilesToGroupApiFilesGroupUploadGroupAddPost<TData = MultiFileUploadResponse>(uploadGroup: string,
    bodyAddFilesToGroupApiFilesGroupUploadGroupAddPost: BodyAddFilesToGroupApiFilesGroupUploadGroupAddPost, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 addFilesToGroupApiFilesGroupUploadGroupAddPost<TData = MultiFileUploadResponse>(uploadGroup: string,
    bodyAddFilesToGroupApiFilesGroupUploadGroupAddPost: BodyAddFilesToGroupApiFilesGroupUploadGroupAddPost, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  addFilesToGroupApiFilesGroupUploadGroupAddPost<TData = MultiFileUploadResponse>(
    uploadGroup: string,
    bodyAddFilesToGroupApiFilesGroupUploadGroupAddPost: BodyAddFilesToGroupApiFilesGroupUploadGroupAddPost, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {const formData = new FormData();
bodyAddFilesToGroupApiFilesGroupUploadGroupAddPost.files.forEach(value => formData.append(`files`, value));

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/files/group/${uploadGroup}/add`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/files/group/${uploadGroup}/add`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/files/group/${uploadGroup}/add`,
      formData,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Refresh all files in a group: new download tokens, new expiry, reset download counts.
 * @summary Refresh Group
 */
 refreshGroupApiFilesGroupUploadGroupRefreshPost<TData = MultiFileUploadResponse>(uploadGroup: string,
    groupRefreshRequest: GroupRefreshRequest, options?: HttpClientBodyOptions): Observable<TData>;
 refreshGroupApiFilesGroupUploadGroupRefreshPost<TData = MultiFileUploadResponse>(uploadGroup: string,
    groupRefreshRequest: GroupRefreshRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 refreshGroupApiFilesGroupUploadGroupRefreshPost<TData = MultiFileUploadResponse>(uploadGroup: string,
    groupRefreshRequest: GroupRefreshRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  refreshGroupApiFilesGroupUploadGroupRefreshPost<TData = MultiFileUploadResponse>(
    uploadGroup: string,
    groupRefreshRequest: GroupRefreshRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/files/group/${uploadGroup}/refresh`,
      groupRefreshRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/files/group/${uploadGroup}/refresh`,
      groupRefreshRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/files/group/${uploadGroup}/refresh`,
      groupRefreshRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Get access configuration for an upload group. Owner only.
 * @summary Get Access Info
 */
 getAccessInfoApiFilesGroupUploadGroupAccessInfoGet<TData = AccessInfoResponse>(uploadGroup: string, options?: HttpClientBodyOptions): Observable<TData>;
 getAccessInfoApiFilesGroupUploadGroupAccessInfoGet<TData = AccessInfoResponse>(uploadGroup: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getAccessInfoApiFilesGroupUploadGroupAccessInfoGet<TData = AccessInfoResponse>(uploadGroup: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getAccessInfoApiFilesGroupUploadGroupAccessInfoGet<TData = AccessInfoResponse>(
    uploadGroup: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/access-info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/access-info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/access-info`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Get download statistics for an upload group. Owner only.
 * @summary Get Group Stats
 */
 getGroupStatsApiFilesGroupUploadGroupStatsGet<TData = DownloadStatsResponse>(uploadGroup: string, options?: HttpClientBodyOptions): Observable<TData>;
 getGroupStatsApiFilesGroupUploadGroupStatsGet<TData = DownloadStatsResponse>(uploadGroup: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getGroupStatsApiFilesGroupUploadGroupStatsGet<TData = DownloadStatsResponse>(uploadGroup: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getGroupStatsApiFilesGroupUploadGroupStatsGet<TData = DownloadStatsResponse>(
    uploadGroup: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/stats`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/stats`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/stats`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * Get download stats visible to email recipients. Requires valid email token.
 * @summary Get Recipient Stats
 */
 getRecipientStatsApiFilesGroupUploadGroupRecipientStatsGet<TData = RecipientStatsResponse>(uploadGroup: string,
    params?: GetRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetParams, options?: HttpClientBodyOptions): Observable<TData>;
 getRecipientStatsApiFilesGroupUploadGroupRecipientStatsGet<TData = RecipientStatsResponse>(uploadGroup: string,
    params?: GetRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getRecipientStatsApiFilesGroupUploadGroupRecipientStatsGet<TData = RecipientStatsResponse>(uploadGroup: string,
    params?: GetRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getRecipientStatsApiFilesGroupUploadGroupRecipientStatsGet<TData = RecipientStatsResponse>(
    uploadGroup: string,
    params?: GetRecipientStatsApiFilesGroupUploadGroupRecipientStatsGetParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/recipient-stats`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/recipient-stats`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/files/group/${uploadGroup}/recipient-stats`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
};

