from collections.abc import Sequence

class CryptContext:
    def __init__(
        self, schemes: Sequence[str] | None = ..., deprecated: str | None = ...
    ) -> None: ...
    def hash(self, secret: str, *args: object, **kwargs: object) -> str: ...
    def verify(
        self, secret: str, hashed: str | None, *args: object, **kwargs: object
    ) -> bool: ...
