apiVersion: apps/v1
kind: Deployment
metadata:
  name: sendr-frontend
  namespace: sendr
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: API_URL
              value: "https://api.dev.sendr.email"