name: 'Terraform CI/CD (DEV)'

on:
  push:
    branches:
      - main
      - DO-implementation
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

env:
  TF_LOG: INFO
  TF_VAR_do_token: ${{ secrets.DO_PAT }}
  TF_VAR_spaces_access_key: ${{ secrets.SPACES_ACCESS_KEY }}
  TF_VAR_spaces_secret_key: ${{ secrets.SPACES_SECRET_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init (DEV)
        id: init
        run: terraform init -backend-config=environments/dev/backend.conf

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan (DEV)
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -var-file=environments/dev/terraform.tfvars
        continue-on-error: true

      # Komentowanie Pull Requesta wynikami Planu
      - name: Update Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style `${{ steps.fmt.outcome }}\`
            #### Terraform Initialization \`${{ steps.init.outcome }}\`
            #### Terraform Validation \`${{ steps.validate.outcome }}\`
            #### Terraform Plan \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply (DEV)
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/DO-implementation') && github.event_name == 'push'
        run: terraform apply -auto-approve -var-file=environments/dev/terraform.tfvars
