name: 'Terraform CI/CD (PROD)'

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'terraform/**'

env:
  TF_LOG: INFO
  TF_VAR_do_token: ${{ secrets.DO_PAT }}
  TF_VAR_spaces_access_key: ${{ secrets.SPACES_ACCESS_KEY }}
  TF_VAR_spaces_secret_key: ${{ secrets.SPACES_SECRET_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}

jobs:
  terraform:
    name: 'Terraform Apply (PROD)'
    # Adding environment protection is a good practice for production
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Set TF_VAR_ghcr_token
        run: echo "TF_VAR_ghcr_token=${{ steps.generate-token.outputs.token }}" >> $GITHUB_ENV

      - name: Terraform Init (PROD)
        id: init
        run: terraform init -backend-config=environments/prod/backend.conf

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply (PROD)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -var-file=environments/prod/terraform.tfvars
