---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sendr-backend
  namespace: sendr
spec:
  rules:
    - host: api.staging.sendr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sendr-backend
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sendr-frontend
  namespace: sendr
spec:
  rules:
    - host: staging.sendr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sendr-frontend
                port:
                  number: 80