apiVersion: apps/v1
kind: Deployment
metadata:
  name: sendr-frontend
  namespace: sendr
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/thephaseless/sendr/frontend:staging-latest